#! /bin/sh

bspc monitor HDMI-A-1 -d 1 2 3 4 5 6
bspc monitor DVI-D-0 -d 7 8 9 10
bspc monitor HDMI-A-0 -d 11

bspc config border_width         0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       false
bspc config initial_polarity second_child
bspc config automatic_scheme longest_side

bspc config external_rules_command ~/.config/bspwm/bspwm-rules

~/.screenlayout/withoutTV.sh
dunst &
compton --config ~/.config/compton/compton.conf &
numlockx &
setxkbmap de
xsetroot -cursor_name left_ptr &
xrdb merge .Xresources &
wmname LG3D &
wal -i ~/dotfiles/background
~/.config/polybar/launch.sh &

# other programms to autostart
keepassxc &
thunderbird &
firefox &
steam &
spotify &
teamspeak3 &

~/dotfiles/scripts/physlock.sh &

xset s 600
xss-lock -- ~/dotfiles/scripts/physlock.sh &

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color "$color1"
