#!/bin/sh
#
# bspwm: external_rules_command

id=${1?};
instance=$3;
class=$2;

case $class in
 (Emacs) echo state=tiled\ layer=normal;;
 (firefox|Firefox-esr|Iceweasel) echo desktop=1;;
 (Gimp*) echo follow=on;;
 (Gitk) echo state=floating\ layer=normal;;
 (XTerm:xterm_keys_help) echo state=floating\ layer=normal;;

 (Thunderbird) echo desktop=8;;
 (Spotify) echo desktop=7;;
 (KeePassXC) echo desktop=10;;
 (TeamSpeak*) echo desktop=7;;
 (Mumble) echo desktop=7;;
 ([sS]team) echo desktop=6\ state=floating;;
# (vlc) echo desktop=11;;
 (TelegramDesktop) echo desktop=8;;

 ([cC]hromium|Chromium-browser) echo desktop=2;;
 ([lL]ibre[oO]ffice*) echo state=tiled\ layer=normal;;
 (stj1) echo state=floating\ layer=above\ sticky=on;;
 ('')
  case $(ps -p "$(xdo pid $id)" -o comm= 2>/dev/null) in
   (spotify) echo desktop=7;;
  esac;;
esac;
